name: Validate Packer Template

on:
  pull_request:
    branches:
        - main
        
jobs:
  validate_packer_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Zip Folders
        run: |
           zip -r webapp.zip /home/runner/work/webapp/webapp
        
      - name: Validate Packer Template
        run: |
           packer validate my-template.json
